### ISSUE TITLE
Postgresql data should not be persisted in container

### ISSUE THREAD

**Issue by davepallot** [AusSRC/WALLABY_database#4]
The database should be mapping data to the host machine in order to persist through container cycles. If the container is deleted, for example, the data is lost. 

docker-compose.yml
```
version: '3.5'

services:
  wallaby_db:
    build: .
    image: wallaby_db
    container_name: wallaby_db
    env_file:
      - psql.env
    ports:
      - 5432:5432
    networks:
      - wallaby_network

networks:
  wallaby_network:
    name: wallaby_network
    driver: bridge
```

Should include:
```
    volumes:
      - /data:/var/lib/postgresql/data
```
The data will need to be migrated to the host for a restart.
